# Generated by Django 4.2.17 on 2024-12-10 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_projeto_usuario_projeto_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em execução', 'Em execução'), ('concluído', 'Concluído')], default='pendente', max_length=20),
        ),
    ]
