# Generated by Django 4.2.17 on 2024-12-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notificacao_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='convite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.convite'),
        ),
    ]
